AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SecretInformation:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: secret_for_rds
      Description: secret_for_rds
      GenerateSecretString:
        SecretStringTemplate: '{"secret_key": "password"}'
        GenerateStringKey: secret_key
        PasswordLength: 16
        ExcludeCharacters: "\"@'%$#&().,{_?<≠^>[:;`+*!]}=~|¥/\\"
      Tags:
        - Key: Name
          Value: password-for-rds
Outputs:
    PssOutput1:
      Value: !Ref SecretInformation
      Export:
        Name: secrets-for-rds